### Question 1
Load the energy data from the file `assets/Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](assets/Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **Energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable]`

Convert `Energy Supply` to gigajoules (**Note: there are 1,000,000 gigajoules in a petajoule**). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g. `'Bolivia (Plurinational State of)'` should be `'Bolivia'`.  `'Switzerland17'` should be `'Switzerland'`.

Next, load the GDP data from the file `assets/world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `assets/scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries, and the rows of the DataFrame should be sorted by "Rank".*

In [82]:
import pandas as pd
import numpy as np

# Filter all warnings. If you would like to see the warnings, please comment the two lines below.
import warnings
warnings.filterwarnings('ignore')

First, let's get the dataframe set up for Energy. This uses a few tips i found on stack overflow and the pandas documentation to clean up the data a bit.

In [102]:
Energy=pd.read_excel('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/Energy Indicators.xls')
Energy = Energy[17:244]
#Energy.columns
Energy.columns = Energy.columns[:2].tolist() + ['Country','Energy Supply','Energy Supply per Capita','% Renewable']
del Energy['Unnamed: 0']
del Energy['Unnamed: 1']

Now we convert to gigajoules for the energy supply column

In [103]:
Energy['Energy Supply'] = Energy['Energy Supply'].apply(lambda x: x*1000000)

In [104]:
Energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
17,Afghanistan,321000000,10,78.6693
18,Albania,102000000,35,100
19,Algeria,1959000000,51,0.55101
20,American Samoa,.................................................,...,0.641026
21,Andorra,9000000,121,88.6957
...,...,...,...,...
239,Viet Nam,2554000000,28,45.3215
240,Wallis and Futuna Islands,0,26,0
241,Yemen,344000000,13,0
242,Zambia,400000000,26,99.7147
243,Zimbabwe,480000000,32,52.5361

In [105]:
Energy['Energy Supply'] = Energy['Energy Supply'].replace(r'[.]*', np.NaN, regex=True)
Energy['% Renewable'] = Energy['% Renewable'].replace(r'[.]*', np.NaN, regex=True)
Energy['Energy Supply per Capita'] = Energy['Energy Supply per Capita'].replace(r'[.]*', np.NaN, regex=True)

In [106]:
Energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
17,Afghanistan,3.210000e+08,10.0,78.669280
18,Albania,1.020000e+08,35.0,100.000000
19,Algeria,1.959000e+09,51.0,0.551010
20,American Samoa,NaN,NaN,0.641026
21,Andorra,9.000000e+06,121.0,88.695650
...,...,...,...,...
239,Viet Nam,2.554000e+09,28.0,45.321520
240,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
241,Yemen,3.440000e+08,13.0,0.000000
242,Zambia,4.000000e+08,26.0,99.714670
243,Zimbabwe,4.800000e+08,32.0,52.536120

~~"Load the energy data from the file assets/Energy Indicators.xls, which is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013, and should be put into a DataFrame with the variable name of Energy.~~

~~Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:~~

~~['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable]~~

~~Convert Energy Supply to gigajoules (Note: there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as np.NaN values."~~

So far the portion of the question above has been completed and all of the items necessary to be delivered have been taken care of. 

Next we need to piece meal through the Country column and rename 

"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"

In [107]:
Energy['Country'] = Energy['Country'].str.replace(r' [(].*[)]',"")

In [108]:
Energy['Country'] = Energy['Country'].str.replace(r"\d{1,3}","")

In [109]:
Energy[90:110]

           Country  Energy Supply  Energy Supply per Capita  % Renewable
107  Guinea-Bissau   2.900000e+07                      17.0     0.000000
108         Guyana   3.400000e+07                      45.0     0.000000
109          Haiti   1.720000e+08                      16.0    12.760180
110       Honduras   2.170000e+08                      28.0    37.763190
111        Hungary   9.470000e+08                      95.0     3.263634
112        Iceland   3.120000e+08                     957.0    99.972400
113          India   3.319500e+10                      26.0    14.969080
114      Indonesia   8.754000e+09                      35.0    12.189040
115           Iran   9.172000e+09                     119.0     5.707721
116           Iraq   2.077000e+09                      61.0     7.871554
117        Ireland   5.480000e+08                     117.0    20.921060
118    Isle of Man   0.000000e+00                       4.0     0.793651
119         Israel   9.970000e+08                     128.0     0.872525
120          Italy   6.530000e+09                     109.0    33.667230
121        Jamaica   1.080000e+08                      39.0     5.615602
122          Japan   1.898400e+10                     149.0    10.232820
123         Jersey   3.000000e+06                      34.0     0.000000
124         Jordan   3.250000e+08                      45.0     0.335979
125     Kazakhstan   3.548000e+09                     208.0     8.112784
126          Kenya   8.730000e+08                      20.0    73.757100

In [110]:
Energy['Country']=Energy['Country'].replace({"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"})

In [111]:
Energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
17,Afghanistan,3.210000e+08,10.0,78.669280
18,Albania,1.020000e+08,35.0,100.000000
19,Algeria,1.959000e+09,51.0,0.551010
20,American Samoa,NaN,NaN,0.641026
21,Andorra,9.000000e+06,121.0,88.695650
...,...,...,...,...
239,Viet Nam,2.554000e+09,28.0,45.321520
240,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
241,Yemen,3.440000e+08,13.0,0.000000
242,Zambia,4.000000e+08,26.0,99.714670
243,Zimbabwe,4.800000e+08,32.0,52.536120

Went through the data and some of the provided columns included numerics on the end of them wasn't a match to the assignment provided notation. Correct them in the line above and ran it. Everything checked out.

In [112]:
#import
GDP = pd.read_csv('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/world_bank.csv',
                 header=4)

In [113]:
GDP['Country Name'] = GDP['Country Name'].replace({"Korea, Rep.": "South Korea",
                                                   "Iran, Islamic Rep.": "Iran",
                                                   "Hong Kong SAR, China": "Hong Kong"})

In [114]:
GDP.rename(columns={'Country Name':'Country'}, inplace=True)

In [125]:
GDP[100:130]

,Country,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
100,IDA & IBRD total,IBT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.309667e+12,2.361282e+12,2.451703e+12,2.565118e+12,2.756906e+12,2.909338e+12,...,1.697394e+13,1.841843e+13,1.944638e+13,1.990883e+13,2.138217e+13,2.265753e+13,2.376510e+13,2.489885e+13,2.594497e+13,2.686382e+13
101,IDA total,IDA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.529855e+11,2.562190e+11,2.702535e+11,2.839714e+11,2.984505e+11,3.120832e+11,...,1.270939e+12,1.353141e+12,1.424120e+12,1.493211e+12,1.582445e+12,1.657974e+12,1.736997e+12,1.832294e+12,1.937910e+12,2.027635e+12
102,IDA blend,IDB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.148437e+11,1.168251e+11,1.216430e+11,1.307341e+11,1.373285e+11,1.450145e+11,...,6.862294e+11,7.280447e+11,7.632609e+11,8.027284e+11,8.516727e+11,8.962054e+11,9.404459e+11,9.897364e+11,1.048144e+12,1.093273e+12
103,Indonesia,IDN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.069046e+10,5.378507e+10,5.481218e+10,5.357724e+10,5.542644e+10,5.595137e+10,...,6.026267e+11,6.408635e+11,6.794031e+11,7.108518e+11,7.550942e+11,8.016818e+11,8.500237e+11,8.972617e+11,9.423391e+11,9.875141e+11
104,IDA only,IDX,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.804125e+11,6.208040e+11,6.566687e+11,6.858835e+11,7.258169e+11,7.562503e+11,7.906358e+11,8.365198e+11,8.832065e+11,9.279495e+11
105,Isle of Man,IMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.109333e+09,4.415768e+09,4.850663e+09,4.953844e+09,5.420292e+09,5.681266e+09,6.036319e+09,6.307562e+09,NaN,NaN
106,India,IND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.425749e+11,1.478826e+11,1.522173e+11,1.613417e+11,1.733664e+11,1.687969e+11,...,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
107,Not classified,INX,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,Ireland,IRL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.249653e+11,2.374346e+11,2.323003e+11,2.192023e+11,2.200761e+11,2.257719e+11,2.261131e+11,2.293562e+11,2.412813e+11,2.601287e+11
109,Iran,IRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.500820e+10,6.072406e+10,6.552689e+10,7.014134e+10,7.608598e+10,8.904776e+10,...,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
110,Iraq,IRQ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.147716e+11,1.163527e+11,1.259263e+11,1.301818e+11,1.385167e+11,1.489698e+11,1.697309e+11,1.808859e+11,1.770543e+11,1.807724e+11
111,Iceland,ISL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.054313e+09,2.052574e+09,2.223219e+09,2.451841e+09,2.694979e+09,2.893645e+09,...,1.296337e+10,1.419397e+10,1.440387e+10,1.372960e+10,1.323689e+10,1.350005e+10,1.365975e+10,1.419193e+10,1.445117e+10,1.502302e+10
112,Israel,ISR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.653195e+10,1.838417e+10,2.025129e+10,2.241731e+10,2.419661e+10,2.639704e+10,...,2.004788e+11,2.127783e+11,2.192881e+11,2.220701e+11,2.343217e+11,2.461086e+11,2.531417e+11,2.616301e+11,2.684316e+11,2.751104e+11
113,Italy,ITA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.455879e+11,5.903657e+11,6.269899e+11,6.621623e+11,6.806877e+11,7.029327e+11,...,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
114,Jamaica,JAM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.391255e+10,1.411178e+10,1.400985e+10,1.338988e+10,1.319051e+10,1.341781e+10,1.333684e+10,1.340991e+10,1.350214e+10,1.362366e+10
115,Jordan,JOR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.110461e+10,2.283007e+10,2.448123e+10,2.582196e+10,2.642538e+10,2.710208e+10,2.782061e+10,2.860772e+10,2.949351e+10,3.019625e+10
116,Japan,JPN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.741600e+11,8.673962e+11,9.446723e+11,1.024720e+12,1.144374e+12,1.210973e+12,...,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
117,Kazakhstan,KAZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.211971e+11,1.319836e+11,1.363391e+11,1.379752e+11,1.480473e+11,1.587068e+11,1.660073e+11,1.756357e+11,1.828368e+11,1.850308e+11
118,Kenya,KEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.364317e+09,4.025008e+09,4.405667e+09,4.792411e+09,5.030329e+09,5.131393e+09,...,3.335057e+10,3.563533e+10,3.571810e+10,3.689928e+10,3.999966e+10,4.244428e+10,4.437760e+10,4.690425e+10,4.940512e+10,5.219611e+10
119,Kyrgyz Republic,KGZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.979135e+09,4.319067e+09,4.681939e+09,4.817074e+09,4.794358e+09,5.079923e+09,5.075445e+09,5.629454e+09,5.855985e+09,6.059146e+09
120,Cambodia,KHM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.014923e+09,9.935578e+09,1.060043e+10,1.060962e+10,1.124228e+10,1.203706e+10,1.291111e+10,1.387686e+10,1.485816e+10,1.590359e+10
121,Kiribati,KIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.377651e+08,1.481201e+08,1.521997e+08,1.511875e+08,1.504311e+08,1.545529e+08,1.588959e+08,1.636195e+08,1.696735e+08,1.750091e+08
122,St. Kitts and Nevis,KNA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.078789e+08,7.279287e+08,7.579826e+08,7.155482e+08,6.924574e+08,7.041954e+08,6.955641e+08,7.360467e+08,7.868565e+08,8.231943e+08
123,South Korea,KOR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.757696e+10,2.893825e+10,2.964966e+10,3.247578e+10,3.493136e+10,3.674434e+10,...,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
124,Kosovo,KSV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.958692e+09,5.319987e+09,5.460691e+09,5.643169e+09,5.829934e+09,6.099252e+09,6.270547e+09,6.486283e+09,6.565321e+09,6.803277e+09
125,Kuwait,KWT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.171234e+11,1.241410e+11,1.272195e+11,1.182173e+11,1.154191e+11,1.265321e+11,1.349166e+11,1.364669e+11,1.342533e+11,1.337163e+11
126,Latin America & Caribbean (excluding high income),LAC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,6.158769e+11,6.581433e+11,6.969364e+11,7.222708e+11,7.752301e+11,8.096191e+11,...,3.924920e+12,4.149097e+12,4.320544e+12,4.261619e+12,4.500356e+12,4.694263e+12,4.843759e+12,4.980645e+12,5.028926e+12,4.972082e+12
127,Lao PDR,LAO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.305667e+09,5.708730e+09,6.155432e+09,6.617199e+09,7.181441e+09,7.758732e+09,8.381309e+09,9.091298e+09,9.774534e+09,1.045828e+10
128,Lebanon,LBN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.673373e+10,2.924779e+10,3.190878e+10,3.519567e+10,3.800995e+10,3.877189e+10,3.962487e+10,3.998150e+10,4.070517e+10,4.131923e+10
129,Liberia,LBR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.426701e+09,1.461512e+09,1.481164e+09,1.514852e+09,1.592897e+09,1.669257e+09,...,9.858721e+08,1.079874e+09,1.157052e+09,1.218377e+09,1.292697e+09,1.398698e+09,1.510516e+09,1.641990e+09,1.653503e+09,1.658424e+09

In [126]:
ScimEn = pd.read_excel('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/scimagojr-3.xlsx')

In [127]:
ScimEn

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
...,...,...,...,...,...,...,...,...
186,187,Guyana,1,1,0,0,0.00,0
187,188,Christmas Island,1,1,0,0,0.00,0
188,189,Reunion,1,1,2,1,2.00,1
189,190,Saint Lucia,1,1,0,0,0.00,0
190,191,Mauritania,1,1,1,0,1.00,1

In [128]:
df = pd.merge(Energy, GDP, how='inner',on=['Country'])

In [131]:
df[70:90]

,Country,Energy Supply,Energy Supply per Capita,% Renewable,Country Code,Indicator Name,Indicator Code,1960,1961,1962,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
70,Guam,NaN,NaN,0.000000,GUM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Guatemala,4.520000e+08,29.0,49.521680,GTM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,6.155035e+09,6.419610e+09,6.646640e+09,...,3.640942e+10,3.870469e+10,3.997462e+10,4.018491e+10,4.133801e+10,4.305852e+10,4.433729e+10,4.597670e+10,4.789585e+10,4.988294e+10
72,Guinea,1.450000e+08,12.0,48.442210,GIN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,4.363171e+09,4.439861e+09,4.659054e+09,4.646000e+09,4.735956e+09,4.921074e+09,5.115166e+09,5.232815e+09,5.253746e+09,5.259000e+09
73,Guinea-Bissau,2.900000e+07,17.0,0.000000,GNB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,7.374643e+08,7.610976e+08,7.854901e+08,8.115244e+08,8.474914e+08,9.265970e+08,9.099368e+08,9.174008e+08,9.407126e+08,9.858365e+08
74,Guyana,3.400000e+07,45.0,0.000000,GUY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.545220e+08,9.992846e+08,1.010326e+09,...,1.919759e+09,2.054533e+09,2.095143e+09,2.164673e+09,2.259288e+09,2.382129e+09,2.496863e+09,2.627240e+09,2.728150e+09,2.810153e+09
75,Haiti,1.720000e+08,16.0,12.760180,HTI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,6.523228e+09,6.741318e+09,6.798211e+09,7.007817e+09,6.622542e+09,6.988353e+09,7.189974e+09,7.495399e+09,7.705005e+09,7.832266e+09
76,Honduras,2.170000e+08,28.0,37.763190,HND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.234327e+09,2.275788e+09,2.406984e+09,...,1.413979e+10,1.501480e+10,1.565017e+10,1.526961e+10,1.583934e+10,1.644689e+10,1.712593e+10,1.760401e+10,1.814714e+10,1.880683e+10
77,Hungary,9.470000e+08,95.0,3.263634,HUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.364672e+11,1.370483e+11,1.381986e+11,1.291340e+11,1.300938e+11,1.323802e+11,1.301444e+11,1.326038e+11,1.374733e+11,1.415135e+11
78,Iceland,3.120000e+08,957.0,99.972400,ISL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.054313e+09,2.052574e+09,2.223219e+09,...,1.296337e+10,1.419397e+10,1.440387e+10,1.372960e+10,1.323689e+10,1.350005e+10,1.365975e+10,1.419193e+10,1.445117e+10,1.502302e+10
79,India,3.319500e+10,26.0,14.969080,IND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.425749e+11,1.478826e+11,1.522173e+11,...,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
80,Indonesia,8.754000e+09,35.0,12.189040,IDN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.069046e+10,5.378507e+10,5.481218e+10,...,6.026267e+11,6.408635e+11,6.794031e+11,7.108518e+11,7.550942e+11,8.016818e+11,8.500237e+11,8.972617e+11,9.423391e+11,9.875141e+11
81,Iran,9.172000e+09,119.0,5.707721,IRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.500820e+10,6.072406e+10,6.552689e+10,...,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
82,Iraq,2.077000e+09,61.0,7.871554,IRQ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.147716e+11,1.163527e+11,1.259263e+11,1.301818e+11,1.385167e+11,1.489698e+11,1.697309e+11,1.808859e+11,1.770543e+11,1.807724e+11
83,Ireland,5.480000e+08,117.0,20.921060,IRL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,2.249653e+11,2.374346e+11,2.323003e+11,2.192023e+11,2.200761e+11,2.257719e+11,2.261131e+11,2.293562e+11,2.412813e+11,2.601287e+11
84,Isle of Man,0.000000e+00,4.0,0.793651,IMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,4.109333e+09,4.415768e+09,4.850663e+09,4.953844e+09,5.420292e+09,5.681266e+09,6.036319e+09,6.307562e+09,NaN,NaN
85,Israel,9.970000e+08,128.0,0.872525,ISR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.653195e+10,1.838417e+10,2.025129e+10,...,2.004788e+11,2.127783e+11,2.192881e+11,2.220701e+11,2.343217e+11,2.461086e+11,2.531417e+11,2.616301e+11,2.684316e+11,2.751104e+11
86,Italy,6.530000e+09,109.0,33.667230,ITA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.455879e+11,5.903657e+11,6.269899e+11,...,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
87,Jamaica,1.080000e+08,39.0,5.615602,JAM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.391255e+10,1.411178e+10,1.400985e+10,1.338988e+10,1.319051e+10,1.341781e+10,1.333684e+10,1.340991e+10,1.350214e+10,1.362366e+10
88,Japan,1.898400e+10,149.0,10.232820,JPN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.741600e+11,8.673962e+11,9.446723e+11,...,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
89,Jordan,3.250000e+08,45.0,0.335979,JOR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,2.110461e+10,2.283007e+10,2.448123e+10,2.582196e+10,2.642538e+10,2.710208e+10,2.782061e+10,2.860772e+10,2.949351e+10,3.019625e+10

In [132]:
df_return = pd.merge(df,ScimEn,how='inner',on=['Country'])

In [133]:
df_return[70:90]

,Country,Energy Supply,Energy Supply per Capita,% Renewable,Country Code,Indicator Name,Indicator Code,1960,1961,1962,...,2013,2014,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
70,Iran,9.172000e+09,119.0,5.707721,IRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.500820e+10,6.072406e+10,6.552689e+10,...,4.445926e+11,4.639027e+11,NaN,13,8896,8819,57470,19125,6.46,72
71,Iraq,2.077000e+09,61.0,7.871554,IRQ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.808859e+11,1.770543e+11,1.807724e+11,66,353,353,1537,134,4.35,19
72,Ireland,5.480000e+08,117.0,20.921060,IRL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,2.293562e+11,2.412813e+11,2.601287e+11,47,974,959,14361,1719,14.74,57
73,Israel,9.970000e+08,128.0,0.872525,ISR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.653195e+10,1.838417e+10,2.025129e+10,...,2.616301e+11,2.684316e+11,2.751104e+11,41,1215,1202,14764,2051,12.15,54
74,Italy,6.530000e+09,109.0,33.667230,ITA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.455879e+11,5.903657e+11,6.269899e+11,...,2.040871e+12,2.033868e+12,2.049316e+12,11,10964,10794,111850,26661,10.20,106
75,Jamaica,1.080000e+08,39.0,5.615602,JAM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.340991e+10,1.350214e+10,1.362366e+10,124,17,17,61,0,3.59,3
76,Japan,1.898400e+10,149.0,10.232820,JPN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.741600e+11,8.673962e+11,9.446723e+11,...,5.644659e+12,5.642884e+12,5.669563e+12,3,30504,30287,223024,61554,7.31,134
77,Jordan,3.250000e+08,45.0,0.335979,JOR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,2.860772e+10,2.949351e+10,3.019625e+10,58,558,554,6992,690,12.53,43
78,Kazakhstan,3.548000e+09,208.0,8.112784,KAZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.756357e+11,1.828368e+11,1.850308e+11,74,206,202,601,99,2.92,10
79,Kenya,8.730000e+08,20.0,73.757100,KEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.364317e+09,4.025008e+09,4.405667e+09,...,4.690425e+10,4.940512e+10,5.219611e+10,84,104,104,1408,23,13.54,14
80,Kuwait,1.475000e+09,410.0,0.000000,KWT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,1.364669e+11,1.342533e+11,1.337163e+11,50,737,731,6101,651,8.28,39
81,Latvia,1.830000e+08,91.0,48.832340,LVA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,2.702069e+10,2.765816e+10,2.818005e+10,69,285,284,452,95,1.59,10
82,Lebanon,2.890000e+08,55.0,6.610478,LBN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,3.998150e+10,4.070517e+10,4.131923e+10,68,293,290,2721,267,9.29,28
83,Lesotho,4.800000e+07,23.0,100.000000,LSO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.085636e+08,2.124529e+08,2.450258e+08,...,2.496306e+09,2.587149e+09,NaN,149,6,6,25,3,4.17,3
84,Liberia,8.300000e+07,19.0,0.000000,LBR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.426701e+09,1.461512e+09,1.481164e+09,...,1.641990e+09,1.653503e+09,1.658424e+09,177,1,1,1,0,1.00,1
85,Libya,7.070000e+08,113.0,0.000000,LBY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,5.012804e+10,3.809731e+10,3.421138e+10,76,186,185,900,52,4.84,16
86,Liechtenstein,3.000000e+06,79.0,96.470590,LIE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,NaN,NaN,NaN,142,6,6,38,0,6.33,2
87,Lithuania,2.820000e+08,95.0,41.033180,LTU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,...,4.233691e+10,4.362076e+10,4.431598e+10,65,412,405,1508,361,3.66,17
88,Luxembourg,1.680000e+08,307.0,45.533240,LUX,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.504569e+09,8.830293e+09,8.950268e+09,...,5.555417e+10,5.781483e+10,6.061841e+10,94,63,62,303,32,4.81,11
89,Madagascar,1.660000e+08,7.0,50.815560,MDG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.651568e+09,3.726375e+09,3.811004e+09,...,9.331595e+09,9.623316e+09,9.913610e+09,138,7,7,87,1,12.43,3

In [134]:
df_return.set_index(['Country'], inplace=True)
df_return = df_return[['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]

In [135]:
df_return

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Afghanistan,163,3,3,0,0,0.00,0,3.210000e+08,10.0,78.669280,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Albania,118,23,23,168,14,7.30,6,1.020000e+08,35.0,100.000000,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
Algeria,42,1215,1197,7393,1413,6.08,40,1.959000e+09,51.0,0.551010,1.446474e+11,1.495654e+11,1.531550e+11,1.556055e+11,1.612073e+11,1.658823e+11,1.715223e+11,1.763249e+11,1.830252e+11,1.901632e+11
American Samoa,180,1,1,0,0,0.00,0,NaN,NaN,0.641026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,168,2,2,13,0,6.50,1,9.000000e+06,121.0,88.695650,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Uruguay,91,71,70,728,80,10.25,15,1.960000e+08,58.0,71.605040,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
Uzbekistan,96,57,56,158,45,2.77,7,1.798000e+09,62.0,21.328410,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
Zambia,123,19,19,14,1,0.74,2,4.000000e+08,26.0,99.714670,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,119,22,21,27,1,1.23,3,4.800000e+08,32.0,52.536120,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [136]:
df_return.sort_values(by='Rank', ascending=True, inplace=True)

In [137]:
df_return[:15]

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

__________________________

Question 2:
determine how many entries were deleted

__________________________________________

In [144]:
ScimEn = pd.read_excel('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/scimagojr-3.xlsx')
GDP = pd.read_csv('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/world_bank.csv',
                  header=4)
#Energy Start
Energy=pd.read_excel('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/Energy Indicators.xls')
Energy = Energy[17:244]
#Energy.columns
Energy.columns = Energy.columns[:2].tolist() + ['Country','Energy Supply','Energy Supply per Capita','% Renewable']
del Energy['Unnamed: 0']
del Energy['Unnamed: 1']
#convert
Energy['Energy Supply'] = Energy['Energy Supply'].apply(lambda x: x*1000000)
#Nan's
Energy['Energy Supply'] = Energy['Energy Supply'].replace(r'[.]*', np.NaN, regex=True)
Energy['% Renewable'] = Energy['% Renewable'].replace(r'[.]*', np.NaN, regex=True)
Energy['Energy Supply per Capita'] = Energy['Energy Supply per Capita'].replace(r'[.]*', np.NaN, regex=True)
#Corrections for country
Energy['Country'] = Energy['Country'].str.replace(r' [(].*[)]',"")
Energy['Country'] = Energy['Country'].str.replace(r"\d{1,3}","")
Energy['Country']=Energy['Country'].replace({"Republic of Korea": "South Korea",
                                             "United States of America": "United States",
                                             "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
                                             "China, Hong Kong Special Administrative Region": "Hong Kong"})
#Energy Done
Shape1 = Energy.shape
Shape2 = GDP.shape
Shape3 = ScimEn.shape

In [145]:
Shape1

(227, 4)

In [150]:
Entries1 = Shape1[0] * Shape1[1]
Entries2 = Shape2[0] * Shape2[1]
Entries3 = Shape3[0] * Shape3[1]
Sum = Entries1 + Entries2 + Entries3 - (15 * 21)

In [152]:
Sum

17961

The number of columns was changed to 21 because we use the country as the index, therefore we need to include that as part of our records.

___________________________________________

### Question 3
What are the top 15 countries for average GDP over the last 10 years?

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [171]:
GDP = pd.read_csv('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/world_bank.csv',
                 header=4)
GDP = GDP [['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]

In [172]:
GDP.set_index(['Country Name'], inplace=True)

In [173]:
GDP

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country Name,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
Andorra,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
Afghanistan,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Angola,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
Albania,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
...,...,...,...,...,...,...,...,...,...,...
"Yemen, Rep.",2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
South Africa,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
"Congo, Dem. Rep.",1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
Zambia,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [182]:
avgGDP = pd.Series(GDP.mean(axis=1))

In [188]:
avgGDP.sort_values(axis=0, ascending=False,inplace=True,)

In [190]:
avgGDP[:15]

Country Name
World                        6.713548e+13
High income                  4.586468e+13
OECD members                 4.514723e+13
Post-demographic dividend    4.292131e+13
IDA & IBRD total             2.202600e+13
Europe & Central Asia        2.117122e+13
Low & middle income          2.081219e+13
Middle income                2.051324e+13
IBRD only                    2.039738e+13
European Union               1.717367e+13
East Asia & Pacific          1.714490e+13
North America                1.703064e+13
Upper middle income          1.576611e+13
United States                1.536434e+13
Late-demographic dividend    1.389504e+13
dtype: float64

In [193]:
#complete answer three as a function
def answer_three():
    GDP = pd.read_csv('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/world_bank.csv',
                      header=4)
    GDP = GDP [['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    GDP.set_index(['Country Name'], inplace=True)
    avgGDP = pd.Series(GDP.mean(axis=1))
    avgGDP.sort_values(axis=0, ascending=False,inplace=True,)
    avgGDP = avgGDP[:15]
    return avgGDP

### Question 4
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [248]:
A3 = answer_three()

In [249]:
key = A3[5:6]
key.index[0]

'Europe & Central Asia'

In [250]:
GDP = pd.read_csv('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/world_bank.csv',
                  header=4)
GDP = GDP [['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]

In [251]:
GDP_Change = GDP.loc[GDP['Country Name'] == key.index[0]]

In [252]:
Change = GDP_Change['2015'] - GDP_Change['2006']
Change.iloc[0]

1787625194095.8008

### Question 5
What is the mean energy supply per capita?

*This function should return a single number.*

In [259]:
#Energy Start
Energy=pd.read_excel('C:/Users/limpertl/Documents/Jupyter Notebooks/DataFrame_Assignment_Week_3/Energy Indicators.xls')
Energy = Energy[17:244]
#Energy.columns
Energy.columns = Energy.columns[:2].tolist() + ['Country','Energy Supply','Energy Supply per Capita','% Renewable']
del Energy['Unnamed: 0']
del Energy['Unnamed: 1']
#convert
Energy['Energy Supply'] = Energy['Energy Supply'].apply(lambda x: x*1000000)
#Nan's
Energy['Energy Supply'] = Energy['Energy Supply'].replace(r'[.]*', np.NaN, regex=True)
Energy['% Renewable'] = Energy['% Renewable'].replace(r'[.]*', np.NaN, regex=True)
Energy['Energy Supply per Capita'] = Energy['Energy Supply per Capita'].replace(r'[.]*', np.NaN, regex=True)
#Corrections for country
Energy['Country'] = Energy['Country'].str.replace(r' [(].*[)]',"")
Energy['Country'] = Energy['Country'].str.replace(r"\d{1,3}","")
Energy['Country']=Energy['Country'].replace({"Republic of Korea": "South Korea",
                                             "United States of America": "United States",
                                             "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
                                             "China, Hong Kong Special Administrative Region": "Hong Kong"})
#Energy Done
NRG = Energy.mean(axis=0,)

In [265]:
NRG.values[1]

90.66666666666667